package com.ccinfom.view;

import com.ccinfom.db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Andronicus
 */
public class addProduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addProduct.class.getName());
    
    private menu parentMenu;
    
    private int productID = -1;
    /**
     * Creates new form addProd
     */
    public addProduct(menu parent) {
        this.parentMenu = parent;
        initComponents();
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        condField = new JComboBox<>(new String[]{"New", "Used", "Refurbished", "Damaged"});
        statusField = new JComboBox<>(new String[]{"In Stock", "Low Stock", "Out of Stock"});
        setTitle("Add New Product");
        
    }
    // constructor for updating product
    public addProduct(menu parent, int id) {
        this(parent);
        this.productID = id;
        this.setTitle("Update Product");
        suppField.setVisible(false);
        prodCodeField.setVisible(false);
        costField.setVisible(false);
        suppLabel.setVisible(false);
        prodCodeLabel.setVisible(false);
        costLabel.setVisible(false);
        pesoLabel.setVisible(false);
        
        loadProductData(id);
    }
    
    public addProduct() {
        initComponents(); 
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        condField = new JComboBox<>(new String[]{"New", "Used", "Refurbished", "Damaged"});
        statusField = new JComboBox<>(new String[]{"In Stock", "Low Stock", "Out of Stock"});
        setTitle("Add New Product");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prodName = new javax.swing.JLabel();
        prodNameField = new javax.swing.JTextField();
        manufacturer = new javax.swing.JLabel();
        manuField = new javax.swing.JTextField();
        Condition = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        intQtyField = new javax.swing.JTextField();
        suppLabel = new javax.swing.JLabel();
        suppField = new javax.swing.JTextField();
        prodCodeLabel = new javax.swing.JLabel();
        prodCodeField = new javax.swing.JTextField();
        costLabel = new javax.swing.JLabel();
        costField = new javax.swing.JTextField();
        pesoLabel = new javax.swing.JLabel();
        submitBttn = new javax.swing.JButton();
        condField = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        statusField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Product ");

        prodName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prodName.setText("Product Name");

        prodNameField.addActionListener(this::prodNameFieldActionPerformed);

        manufacturer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manufacturer.setText("Manufacturer");

        Condition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Condition.setText("Condition");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Initial Quantity");

        intQtyField.addActionListener(this::intQtyFieldActionPerformed);

        suppLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suppLabel.setText("Supplier ID");

        suppField.addActionListener(this::suppFieldActionPerformed);

        prodCodeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prodCodeLabel.setText("Product Code");

        costLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        costLabel.setText("Unit Cost");

        pesoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pesoLabel.setText("Php");

        submitBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitBttn.setText("Submit");
        submitBttn.addActionListener(this::submitBttnActionPerformed);

        condField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Used", "Refurbished", "Damaged" }));
        condField.addActionListener(this::condFieldActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Status");

        statusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Stock", "Low Stock", "Out of Stock" }));
        statusField.addActionListener(this::statusFieldActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(submitBttn)
                .addGap(24, 64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(costLabel)
                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Condition)
                        .addComponent(manufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manuField)
                        .addComponent(prodCodeLabel)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(pesoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(costField))
                        .addComponent(prodNameField)
                        .addComponent(prodName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(condField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(intQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(suppLabel)
                    .addComponent(prodCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prodName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manufacturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Condition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(condField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(suppLabel)
                .addGap(1, 1, 1)
                .addComponent(suppField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prodCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoLabel))
                .addGap(27, 27, 27)
                .addComponent(submitBttn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodNameFieldActionPerformed

    private void suppFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppFieldActionPerformed

    private void condFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_condFieldActionPerformed

    private void submitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttnActionPerformed
        String name = prodNameField.getText().trim();
    String manufacturer = manuField.getText().trim();
    
    // Get values from JComboBoxes
    String condition = condField.getSelectedItem().toString(); 
    String status = statusField.getSelectedItem().toString(); 
    
    // Variables for parsing
    int quantity;
    
    try {
        quantity = Integer.parseInt(intQtyField.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Quantity must be a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (name.isEmpty() || manufacturer.isEmpty() || condition.isEmpty() || status.isEmpty() || quantity < 0) {
        JOptionPane.showMessageDialog(this, "Please ensure product name, manufacturer, condition, status, and quantity are valid.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    Connection conn = null;
    try {
        conn = DBConnection.getConnection();
        
     
        if (this.productID == -1) {
            
            String supplierCode = suppField.getText().trim();
            int supplierId; 
            double unitCost; 

            try {
                supplierId = Integer.parseInt(suppField.getText().trim());
                unitCost = Double.parseDouble(costField.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Supplier ID and Unit Cost must be valid numbers for adding a product.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (supplierCode.isEmpty() || supplierId <= 0 || unitCost <= 0) {
                 JOptionPane.showMessageDialog(this, "Supplier details are required for a new product.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                 return;
            }

            conn.setAutoCommit(false); 
            int newProductId = -1;

            // Insert into Products table
            String productSql = "INSERT INTO Products (ProductName, Manufacturer, `Condition`, AvailableQuantity, InventoryStatus) VALUES (?, ?, ?, ?, ?)";
            try (PreparedStatement productStmt = conn.prepareStatement(productSql, Statement.RETURN_GENERATED_KEYS)) {
                productStmt.setString(1, name);
                productStmt.setString(2, manufacturer);
                productStmt.setString(3, condition); 
                productStmt.setInt(4, quantity);
                productStmt.setString(5, status); 

                productStmt.executeUpdate();
                ResultSet keys = productStmt.getGeneratedKeys();
                if (keys.next()) {
                    newProductId = keys.getInt(1);
                }
            }

            if (newProductId == -1) {
                throw new SQLException("Failed to retrieve generated Product ID.");
            }

            // Link to SupplierProducts table
            String linkSql = "INSERT INTO SupplierProducts (SupplierID, ProductID, SupplierProductCode, UnitCost) VALUES (?, ?, ?, ?)";
            try (PreparedStatement linkStmt = conn.prepareStatement(linkSql)) {
                linkStmt.setInt(1, supplierId);
                linkStmt.setInt(2, newProductId);
                linkStmt.setString(3, supplierCode);
                linkStmt.setDouble(4, unitCost);
                linkStmt.executeUpdate();
            }

            conn.commit(); 
            JOptionPane.showMessageDialog(this, "Product added and linked successfully!\nNew Product ID: " + newProductId, "Success", JOptionPane.INFORMATION_MESSAGE);


        } else {
          
            
            String updateSql = "UPDATE Products SET ProductName=?, Manufacturer=?, `Condition`=?, AvailableQuantity=?, InventoryStatus=? WHERE ProductID=?";

            try (PreparedStatement stmt = conn.prepareStatement(updateSql)) {
                stmt.setString(1, name);
                stmt.setString(2, manufacturer);
                stmt.setString(3, condition); 
                stmt.setInt(4, quantity);
                stmt.setString(5, status); 
                stmt.setInt(6, this.productID); // Set the WHERE clause ID
                
                int rows = stmt.executeUpdate();
                if (rows > 0) {
                     JOptionPane.showMessageDialog(this, "Product updated successfully!\nProduct ID: " + this.productID, "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                     JOptionPane.showMessageDialog(this, "Product update failed. Record not found.", "Update Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        // Refresh the main menu table and close the window (common to both Add/Update)
        if (parentMenu != null) {
            parentMenu.loadProductData(); 
        }
        this.dispose();

    } catch (SQLException e) {
        // Rollback only if a connection exists and we were attempting an INSERT
        if (conn != null && this.productID == -1) {
            try {
                conn.rollback(); 
            } catch (SQLException rollbackEx) {
                logger.log(java.util.logging.Level.SEVERE, "Rollback failed", rollbackEx);
            }
        }
        logger.log(java.util.logging.Level.SEVERE, "Error processing product record", e);
        JOptionPane.showMessageDialog(this, 
            "Database Error: Product not saved/updated.\n" + e.getMessage(), 
            "SQL Transaction Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try {
                conn.setAutoCommit(true);
                conn.close();
            } catch (SQLException closeEx) {
                logger.log(java.util.logging.Level.WARNING, "Failed to close connection or reset auto-commit", closeEx);
            }
        }
    }
    
    }//GEN-LAST:event_submitBttnActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void intQtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intQtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intQtyFieldActionPerformed

    
    public void loadProductData(int id) {
        String sql = "SELECT ProductName, Manufacturer, `Condition`, AvailableQuantity, InventoryStatus FROM Products WHERE ProductID = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    // Populate fields with current data
                    prodNameField.setText(rs.getString("ProductName"));
                    manuField.setText(rs.getString("Manufacturer"));
                    condField.setSelectedItem(rs.getString("Condition"));
                    intQtyField.setText(String.valueOf(rs.getInt("AvailableQuantity")));
                    statusField.setSelectedItem(rs.getString("InventoryStatus"));
                }
            }
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading product data for update.", e);
            JOptionPane.showMessageDialog(this, "Error loading product data: " + e.getMessage(), "DB Load Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Condition;
    private javax.swing.JComboBox<String> condField;
    private javax.swing.JTextField costField;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField intQtyField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField manuField;
    private javax.swing.JLabel manufacturer;
    private javax.swing.JLabel pesoLabel;
    private javax.swing.JTextField prodCodeField;
    private javax.swing.JLabel prodCodeLabel;
    private javax.swing.JLabel prodName;
    private javax.swing.JTextField prodNameField;
    private javax.swing.JComboBox<String> statusField;
    private javax.swing.JButton submitBttn;
    private javax.swing.JTextField suppField;
    private javax.swing.JLabel suppLabel;
    // End of variables declaration//GEN-END:variables
}
