package com.ccinfom.view;

import com.ccinfom.db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Andronicus
 */
public class addProduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addProduct.class.getName());
    
    private menu parentMenu;
    /**
     * Creates new form addProd
     */
    public addProduct(menu parent) {
        this.parentMenu = parent;
        initComponents();
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        condField = new JComboBox<>(new String[]{"New", "Used", "Refurbished", "Damaged"});
        statusField = new JComboBox<>(new String[]{"In Stock", "Low Stock", "Out of Stock"});
        setTitle("Add New Product");
        
    }
    
    public addProduct() {
        initComponents(); 
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        condField = new JComboBox<>(new String[]{"New", "Used", "Refurbished", "Damaged"});
        statusField = new JComboBox<>(new String[]{"In Stock", "Low Stock", "Out of Stock"});
        setTitle("Add New Product");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prodName = new javax.swing.JLabel();
        prodNameField = new javax.swing.JTextField();
        manufacturer = new javax.swing.JLabel();
        manuField = new javax.swing.JTextField();
        Condition = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        intQtyField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        suppField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prodCodeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        costField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        submitBttn = new javax.swing.JButton();
        condField = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        statusField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Product ");

        prodName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prodName.setText("Product Name");

        prodNameField.addActionListener(this::prodNameFieldActionPerformed);

        manufacturer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manufacturer.setText("Manufacturer");

        Condition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Condition.setText("Condition");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Initial Quantity");

        intQtyField.addActionListener(this::intQtyFieldActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Supplier ID");

        suppField.addActionListener(this::suppFieldActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Product Code");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Unit Cost");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Php");

        submitBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitBttn.setText("Submit");
        submitBttn.addActionListener(this::submitBttnActionPerformed);

        condField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Used", "Refurbished", "Damaged" }));
        condField.addActionListener(this::condFieldActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Status");

        statusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Stock", "Low Stock", "Out of Stock" }));
        statusField.addActionListener(this::statusFieldActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(submitBttn)
                .addGap(24, 64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Condition)
                        .addComponent(manufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manuField)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(costField))
                        .addComponent(prodNameField)
                        .addComponent(prodName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(condField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(intQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(prodCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prodName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manufacturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Condition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(condField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(suppField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addComponent(submitBttn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodNameFieldActionPerformed

    private void suppFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppFieldActionPerformed

    private void condFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_condFieldActionPerformed

    private void submitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttnActionPerformed
        String name = prodNameField.getText().trim();
        String manufacturer = manuField.getText().trim();
        String condition = condField.getSelectedItem().toString();
        String status = statusField.getSelectedItem().toString();
        String supplierCode = suppField.getText().trim();

     
        int quantity, supplierId;
        double unitCost;
        
        try {
            quantity = Integer.parseInt(intQtyField.getText().trim());
            supplierId = Integer.parseInt(suppField.getText().trim());
            unitCost = Double.parseDouble(costField.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity, Supplier ID, and Unit Cost must be valid numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

       
        if (name.isEmpty() || manufacturer.isEmpty() || condition.isEmpty() || status.isEmpty() || supplierCode.isEmpty() || quantity <= 0 || supplierId <= 0) {
            JOptionPane.showMessageDialog(this, "Please ensure all fields are filled and valid.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection conn = null;
        try {
            conn = DBConnection.getConnection();
            conn.setAutoCommit(false); // Start transaction
            int newProductId = -1;

            
            String productSql = "INSERT INTO Products (ProductName, Manufacturer, `Condition`, AvailableQuantity, InventoryStatus) VALUES (?, ?, ?, ?, ?)";
            try (PreparedStatement productStmt = conn.prepareStatement(productSql, Statement.RETURN_GENERATED_KEYS)) {
                productStmt.setString(1, name);
                productStmt.setString(2, manufacturer);
                productStmt.setString(3, condition); 
                productStmt.setInt(4, quantity);
                productStmt.setString(5, status); 

                int rows = productStmt.executeUpdate();
                
                if (rows > 0) {
                    ResultSet keys = productStmt.getGeneratedKeys();
                    if (keys.next()) {
                        newProductId = keys.getInt(1);
                    }
                }
            }

            if (newProductId == -1) {
                throw new SQLException("Failed to retrieve generated Product ID.");
            }

            // Link to SupplierProducts table 
            String linkSql = "INSERT INTO SupplierProducts (SupplierID, ProductID, SupplierProductCode, UnitCost) VALUES (?, ?, ?, ?)";
            try (PreparedStatement linkStmt = conn.prepareStatement(linkSql)) {
                linkStmt.setInt(1, supplierId);
                linkStmt.setInt(2, newProductId);
                linkStmt.setString(3, supplierCode);
                linkStmt.setDouble(4, unitCost);
                linkStmt.executeUpdate();
            }

            conn.commit(); 
            
            JOptionPane.showMessageDialog(this, 
                "Product added and linked successfully!\nNew Product ID: " + newProductId, 
                "Success", JOptionPane.INFORMATION_MESSAGE);

            if (parentMenu != null) {
                parentMenu.loadProductData(); 
            }
            this.dispose();

        } catch (SQLException e) {
            
            if (conn != null) {
                try {
                    conn.rollback(); 
                } catch (SQLException rollbackEx) {
                    logger.log(java.util.logging.Level.SEVERE, "Rollback failed", rollbackEx);
                }
            }
            logger.log(java.util.logging.Level.SEVERE, "Error adding product", e);
            JOptionPane.showMessageDialog(this, 
                "Database Error: Product not added.\n" + e.getMessage(), 
                "SQL Transaction Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (conn != null) {
                try {
                    conn.setAutoCommit(true);
                    conn.close();
                } catch (SQLException closeEx) {
                    logger.log(java.util.logging.Level.WARNING, "Failed to close connection or reset auto-commit", closeEx);
                }
            }
        }
    
    }//GEN-LAST:event_submitBttnActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void intQtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intQtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intQtyFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Condition;
    private javax.swing.JComboBox<String> condField;
    private javax.swing.JTextField costField;
    private javax.swing.JTextField intQtyField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField manuField;
    private javax.swing.JLabel manufacturer;
    private javax.swing.JTextField prodCodeField;
    private javax.swing.JLabel prodName;
    private javax.swing.JTextField prodNameField;
    private javax.swing.JComboBox<String> statusField;
    private javax.swing.JButton submitBttn;
    private javax.swing.JTextField suppField;
    // End of variables declaration//GEN-END:variables
}
