package com.ccinfom.view;

import com.ccinfom.db.DBConnection;
import java.sql.*;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Andronicus
 */
public class addTransport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addTransport.class.getName());

    private menu parentMenu;
    private int transportID = -1;
    /**
     * Creates new form addTransport
     */
    
    // constructor for adding
    public addTransport(menu parent) {
        this.parentMenu = parent;
        initComponents();
        this.setTitle("Add Transport Service");
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    // constructor for updating
    public addTransport(menu parent, int id) {
        this(parent);
        this.transportID = id;
        this.setTitle("Update Transport Service");
        loadTransportData(id);
    }
    public addTransport() {
        initComponents();
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contactPersonField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        courierField = new javax.swing.JTextField();
        submitBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Transport Service  ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Contact Person");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Courier Company");

        submitBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitBttn.setText("Submit");
        submitBttn.addActionListener(this::submitBttnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(contactPersonField)
                            .addComponent(phoneField)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courierField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(submitBttn)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactPersonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitBttn)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttnActionPerformed
        String contactPerson = contactPersonField.getText().trim();
        String phone = phoneField.getText().trim();
        String courierCompany = courierField.getText().trim();

        // Simple Validation
        if (contactPerson.isEmpty() || phone.isEmpty() || courierCompany.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in Contact Person, Phone, and Courier Company.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql;
        String successMessage;

        if (this.transportID == -1) {
            // ADD NEW RECORD (INSERT)
            sql = "INSERT INTO Transports (ContactPerson, Phone, CourierCompany) VALUES (?, ?, ?)";
            successMessage = "Transport record added successfully!";
        } else {
            // UPDATE EXISTING RECORD (UPDATE)
            sql = "UPDATE Transports SET ContactPerson=?, Phone=?, CourierCompany=? WHERE TransportID=?";
            successMessage = "Transport record updated successfully!";
        }

        try (Connection conn = DBConnection.getConnection();
             // Only use Statement.RETURN_GENERATED_KEYS if it's an INSERT
             PreparedStatement stmt = conn.prepareStatement(sql, this.transportID == -1 ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS)) {

            // Set parameters 1 through 3 (same for INSERT and UPDATE)
            stmt.setString(1, contactPerson);
            stmt.setString(2, phone);
            stmt.setString(3, courierCompany);

            if (this.transportID != -1) {
                // Set the 4th parameter for the WHERE clause in the UPDATE statement
                stmt.setInt(4, this.transportID); 
            }

            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                int finalID = this.transportID;

                // Only retrieve generated keys if it was an INSERT
                if (this.transportID == -1) {
                     ResultSet keys = stmt.getGeneratedKeys();
                     if (keys.next()) {
                         finalID = keys.getInt(1);
                     }
                }

                JOptionPane.showMessageDialog(this, 
                    successMessage + "\nTransport ID: " + finalID, 
                    "Success", JOptionPane.INFORMATION_MESSAGE);

                // Refresh the main table
                if (parentMenu != null) {
                    parentMenu.loadTransportData(); 
                }

                // Close the window
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Failed to process transport record.", "DB Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "SQL Error processing transport record.", e);
            JOptionPane.showMessageDialog(this, 
                "Database Error: " + e.getMessage(), 
                "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_submitBttnActionPerformed

    public void loadTransportData(int id) {
        String sql = "SELECT ContactPerson, Phone, CourierCompany FROM Transports WHERE TransportID = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    // Populate fields with current data
                    contactPersonField.setText(rs.getString("ContactPerson"));
                    phoneField.setText(rs.getString("Phone"));
                    courierField.setText(rs.getString("CourierCompany"));
                }
            }
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading transport data for update.", e);
            JOptionPane.showMessageDialog(this, "Error loading transport data: " + e.getMessage(), "DB Load Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addTransport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactPersonField;
    private javax.swing.JTextField courierField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton submitBttn;
    // End of variables declaration//GEN-END:variables
}
