package com.ccinfom.view;

import com.ccinfom.model.*;
import com.ccinfom.db.DBConnection;
import com.ccinfom.util.PdfExporter;
import java.sql.*;
import java.time.LocalDate;
import java.util.List; 
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.io.File;


public class menu extends javax.swing.JFrame {
    

    private DefaultTableModel productTableModel;
    private DefaultTableModel customerTableModel; 
    private DefaultTableModel supplierTableModel; 
    private DefaultTableModel transportTableModel;
    private DefaultTableModel returnRequestTableModel;
    private DefaultTableModel orderTableModel;
    private DefaultTableModel stockTableModel;
    private DefaultTableModel transportLogTableModel;

    private javax.swing.JTable returnRequestTable;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable stockTable;
    private javax.swing.JTable transportLogTable;

    private javax.swing.JTextField searchReturn;
    private javax.swing.JTextField searchOrder;
    private javax.swing.JTextField searchStock;
    private javax.swing.JTextField searchTransLog;

    private javax.swing.JButton addReturnRequestBtn;
    private javax.swing.JButton addOrderBtn;
    private javax.swing.JButton addStockBtn;
    private javax.swing.JButton addTransportLogBtn;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());
    
    private static final String REPORTS_DIR = "reports/";

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setResizable(false);
        

        initProductTable(); // initialize product 
        loadProductData();
        initCustomerTable(); // initialize customer
        loadCustomerData();
        initSupplierTable(); // initialize supplier
        loadSupplierData();
        initTransportTable(); // initialize transport
        loadTransportData();
        // Setup remaining panels (Return Request, Order, Stock Log, Transport Log)
        setupReturnRequestPanel();
        initReturnRequestTable();
        loadReturnRequestData();

        setupOrderPanel();
        initOrderTable();
        loadOrderData();

        setupStockPanel();
        initStockTable();
        loadStockData();

        setupTransportLogPanel();
        initTransportLogTable();
        loadTransportLogData();
    }
    
    private void checkReportDirectory() {
        File dir = new File(REPORTS_DIR);
        if (!dir.exists()) {
            dir.mkdirs();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        productPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        updateProduct = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        prodTable = new javax.swing.JTable();
        searchProd = new javax.swing.JTextField();
        customerPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        updateCustomer = new javax.swing.JButton();
        addCustomer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        searchCust = new javax.swing.JTextField();
        supplierPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        suppLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        updateSupplier = new javax.swing.JButton();
        addSupplier = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        searchSupp = new javax.swing.JTextField();
        transportPanel = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        updateTransport = new javax.swing.JButton();
        addTransport = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        transportTable = new javax.swing.JTable();
        searchTranspo = new javax.swing.JTextField();
        returnRequestPanel = new javax.swing.JPanel();
        salesPanel = new javax.swing.JPanel();
        stockPanel = new javax.swing.JPanel();
        transLogPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        returnsAnalysisMenu = new javax.swing.JMenuItem();
        customerEngagementMenu = new javax.swing.JMenuItem();
        suppOrderMenu = new javax.swing.JMenuItem();
        transEfficiencyMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Model Kit Store Return System");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");

        jLabel106.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel106.setText("Product Menu");

        updateProduct.setText("Update");
        updateProduct.addActionListener(this::updateProductActionPerformed);

        addProduct.setText("Add");
        addProduct.addActionListener(this::addProductActionPerformed);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProduct))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProduct)
                    .addComponent(updateProduct))
                .addGap(70, 70, 70))
        );

        prodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(prodTable);

        searchProd.setForeground(new java.awt.Color(204, 204, 204));
        searchProd.setText("Search");
        searchProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchProdMouseClicked(evt);
            }
        });
        searchProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchProdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel106)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel106)
                            .addComponent(searchProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanelLayout.createSequentialGroup()
                    .addGap(0, 73, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanelLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Product", productPanel);

        jLabel102.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel102.setText("Customer Menu");

        updateCustomer.setText("Update");
        updateCustomer.addActionListener(this::updateCustomerActionPerformed);

        addCustomer.setText("Add");
        addCustomer.addActionListener(this::addCustomerActionPerformed);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCustomer))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomer)
                    .addComponent(updateCustomer))
                .addGap(70, 70, 70))
        );

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(customerTable);

        searchCust.setForeground(new java.awt.Color(204, 204, 204));
        searchCust.setText("Search");
        searchCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchCustMouseClicked(evt);
            }
        });
        searchCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchCustKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel102)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchCust, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel102)
                            .addComponent(searchCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", customerPanel);

        suppLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suppLabel.setText("Supplier Menu");

        updateSupplier.setText("Update");
        updateSupplier.addActionListener(this::updateSupplierActionPerformed);

        addSupplier.setText("Add");
        addSupplier.addActionListener(this::addSupplierActionPerformed);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateSupplier))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSupplier)
                    .addComponent(updateSupplier))
                .addGap(70, 70, 70))
        );

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(supplierTable);

        searchSupp.setForeground(new java.awt.Color(204, 204, 204));
        searchSupp.setText("Search");
        searchSupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchSuppMouseClicked(evt);
            }
        });
        searchSupp.addActionListener(this::searchSuppActionPerformed);
        searchSupp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchSuppKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(suppLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suppLabel)
                            .addComponent(searchSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout supplierPanelLayout = new javax.swing.GroupLayout(supplierPanel);
        supplierPanel.setLayout(supplierPanelLayout);
        supplierPanelLayout.setHorizontalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supplierPanelLayout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        supplierPanelLayout.setVerticalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supplierPanelLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Supplier", supplierPanel);

        jLabel104.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel104.setText("Transport Menu");

        updateTransport.setText("Update");
        updateTransport.addActionListener(this::updateTransportActionPerformed);

        addTransport.setText("Add");
        addTransport.addActionListener(this::addTransportActionPerformed);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTransport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateTransport))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTransport)
                    .addComponent(updateTransport))
                .addGap(70, 70, 70))
        );

        transportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(transportTable);

        searchTranspo.setForeground(new java.awt.Color(204, 204, 204));
        searchTranspo.setText("Search");
        searchTranspo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTranspoMouseClicked(evt);
            }
        });
        searchTranspo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTranspoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel104)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchTranspo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel104)
                            .addComponent(searchTranspo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout transportPanelLayout = new javax.swing.GroupLayout(transportPanel);
        transportPanel.setLayout(transportPanelLayout);
        transportPanelLayout.setHorizontalGroup(
            transportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(transportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transportPanelLayout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        transportPanelLayout.setVerticalGroup(
            transportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(transportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transportPanelLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Transport", transportPanel);

        javax.swing.GroupLayout returnRequestPanelLayout = new javax.swing.GroupLayout(returnRequestPanel);
        returnRequestPanel.setLayout(returnRequestPanelLayout);
        returnRequestPanelLayout.setHorizontalGroup(
            returnRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        returnRequestPanelLayout.setVerticalGroup(
            returnRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Return Request", returnRequestPanel);

        javax.swing.GroupLayout salesPanelLayout = new javax.swing.GroupLayout(salesPanel);
        salesPanel.setLayout(salesPanelLayout);
        salesPanelLayout.setHorizontalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        salesPanelLayout.setVerticalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Order", salesPanel);

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stock Log", stockPanel);

        javax.swing.GroupLayout transLogPanelLayout = new javax.swing.GroupLayout(transLogPanel);
        transLogPanel.setLayout(transLogPanelLayout);
        transLogPanelLayout.setHorizontalGroup(
            transLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        transLogPanelLayout.setVerticalGroup(
            transLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Transport Log", transLogPanel);

        jLabel2.setFont(new java.awt.Font("sansserif", 2, 24)); // NOI18N
        jLabel2.setText("Model Kit Store Return System");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Menu");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(182, 182, 182))
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenu2.setText("Generate Reports");

        returnsAnalysisMenu.setLabel("Returns Analysis");
        returnsAnalysisMenu.addActionListener(this::returnsAnalysisMenuActionPerformed);
        jMenu2.add(returnsAnalysisMenu);

        customerEngagementMenu.setText("Customer Engagement");
        customerEngagementMenu.addActionListener(this::customerEngagementMenuActionPerformed);
        jMenu2.add(customerEngagementMenu);

        suppOrderMenu.setText("Supplier Order");
        suppOrderMenu.addActionListener(this::suppOrderMenuActionPerformed);
        jMenu2.add(suppOrderMenu);

        transEfficiencyMenu.setText("Transport Efficiency");
        transEfficiencyMenu.addActionListener(this::transEfficiencyMenuActionPerformed);
        jMenu2.add(transEfficiencyMenu);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        addCustomer addCust = new addCustomer(this);
        addCust.setVisible(true);
    }//GEN-LAST:event_addCustomerActionPerformed

    private void addTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTransportActionPerformed
        addTransport addTranspo = new addTransport(this);
        addTranspo.setVisible(true);
    }//GEN-LAST:event_addTransportActionPerformed

    private void addSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierActionPerformed
        addSupplier addSup = new addSupplier(this);
        addSup.setVisible(true);
    }//GEN-LAST:event_addSupplierActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        addProduct addProd = new addProduct(this);
        addProd.setVisible(true);
        
        
    }//GEN-LAST:event_addProductActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
    JTable productTable = prodTable; // Use your actual table variable name
    
    int selectedRow = productTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product row to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get the Primary Key (ProductID) from the first column (index 0)
    Object idObject = productTable.getModel().getValueAt(selectedRow, 0);
    int productID = Integer.parseInt(idObject.toString());
    
    // Open the Update Form
    addProduct updateForm = new addProduct(this, productID);
    updateForm.setVisible(true);

    }//GEN-LAST:event_updateProductActionPerformed

    private void updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerActionPerformed
        JTable custTable = customerTable;
        
        int selectedRow = custTable.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a customer row to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        Object idObject = custTable.getModel().getValueAt(selectedRow,0);
        int customerID = Integer.parseInt(idObject.toString());
      
        addCustomer updateForm = new addCustomer(this, customerID);
        updateForm.setVisible(true);
        
    }//GEN-LAST:event_updateCustomerActionPerformed

    private void updateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplierActionPerformed
        JTable suppTable = supplierTable; // Use your actual table variable name
    
        int selectedRow = suppTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a supplier row to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the Primary Key (SupplierID) from the first column (index 0)
        Object idObject = suppTable.getModel().getValueAt(selectedRow, 0);
        int supplierID = Integer.parseInt(idObject.toString());

        // Open the Update Form
        // Pass the parent menu AND the ID
        addSupplier updateForm = new addSupplier(this, supplierID);
        updateForm.setVisible(true);
    }//GEN-LAST:event_updateSupplierActionPerformed

    private void updateTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTransportActionPerformed
        JTable transpoTable = transportTable; // Use your actual table variable name
    
        int selectedRow = transpoTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a transport row to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the Primary Key (TransportID) from the first column (index 0)
        Object idObject = transpoTable.getModel().getValueAt(selectedRow, 0);
        int transportID = Integer.parseInt(idObject.toString());

        // Open the Update Form
        // Pass the parent menu AND the ID
        addTransport updateForm = new addTransport(this, transportID);
        updateForm.setVisible(true);
    }//GEN-LAST:event_updateTransportActionPerformed

    private void searchSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSuppActionPerformed

    private void searchProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchProdKeyReleased
        DefaultTableModel ob = (DefaultTableModel) prodTable.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        prodTable.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(searchProd.getText()));
    }//GEN-LAST:event_searchProdKeyReleased

    private void searchProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchProdMouseClicked
        searchProd.setText("");
    }//GEN-LAST:event_searchProdMouseClicked

    private void searchCustKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustKeyReleased
        DefaultTableModel ob = (DefaultTableModel) customerTable.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        customerTable.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(searchCust.getText()));
    }//GEN-LAST:event_searchCustKeyReleased

    private void searchCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustMouseClicked
        searchCust.setText("");
    }//GEN-LAST:event_searchCustMouseClicked

    private void searchSuppKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchSuppKeyReleased
        DefaultTableModel ob = (DefaultTableModel) supplierTable.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        supplierTable.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(searchSupp.getText()));
    }//GEN-LAST:event_searchSuppKeyReleased

    private void searchSuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchSuppMouseClicked
        searchSupp.setText("");
    }//GEN-LAST:event_searchSuppMouseClicked

    private void searchTranspoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTranspoMouseClicked
        searchTranspo.setText("");
    }//GEN-LAST:event_searchTranspoMouseClicked

    private void searchTranspoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTranspoKeyReleased
        DefaultTableModel ob = (DefaultTableModel) transportTable.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        transportTable.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(searchTranspo.getText()));
    }//GEN-LAST:event_searchTranspoKeyReleased

    private void suppOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppOrderMenuActionPerformed
        promptSupplierOrderReport();      
    }//GEN-LAST:event_suppOrderMenuActionPerformed

    private void returnsAnalysisMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnsAnalysisMenuActionPerformed
        generateReturnsAnalysisReport();       
    }//GEN-LAST:event_returnsAnalysisMenuActionPerformed

    private void customerEngagementMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerEngagementMenuActionPerformed
        promptCustomerEngagementReport();        // TODO add your handling code here:
    }//GEN-LAST:event_customerEngagementMenuActionPerformed

    private void transEfficiencyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transEfficiencyMenuActionPerformed
        promptTransportEfficiencyReport();      
    }//GEN-LAST:event_transEfficiencyMenuActionPerformed

    private void initProductTable() {
   
    String[] columnHeaders = {"ID", "Name", "Manufacturer", 
                              "Condition", "Available Qty", "Status"};
                                
    productTableModel = new DefaultTableModel(columnHeaders, 0) {
    
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };
    prodTable.setModel(productTableModel);
}
   
    
    public void loadProductData() { 
    productTableModel.setRowCount(0); 
    
   
    String sql = "SELECT ProductID, ProductName, Manufacturer, `Condition`, AvailableQuantity, InventoryStatus FROM Products";
    
    try (Connection conn = DBConnection.getConnection(); 
         Statement stmt = conn.createStatement();         
         ResultSet rs = stmt.executeQuery(sql)) {       

        while (rs.next()) {
            Product product = new Product(
                rs.getInt("ProductID"),
                rs.getString("ProductName"),
                rs.getString("Manufacturer"),
                rs.getString("Condition"),
                rs.getInt("AvailableQuantity"),
                rs.getString("InventoryStatus")
            );

            
            Object[] rowData = {
                product.getProductID(),
                product.getProductName(),
                product.getManufacturer(),
                product.getCondition(),
                product.getAvailableQuantity(),
                product.getInventoryStatus()
            };
            productTableModel.addRow(rowData);
        }
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Product DB Read Error: " + e.getMessage() + 
            "\nCheck your SQL query and DBConnection credentials.", 
            "SQL Error - Products", 
            JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void initCustomerTable() {
    
    String[] columnHeaders = {"ID", "First Name", "Last Name", "Phone", "Email", "Address"}; 
    
    customerTableModel = new DefaultTableModel(columnHeaders, 0) {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };
    customerTable.setModel(customerTableModel); // Assuming jTable1 is for Customers
}
    
   public void loadCustomerData() {
    customerTableModel.setRowCount(0);
    
    // Query now selects ALL 6 fields from the Customers table
    String sql = "SELECT CustomerID, FirstName, LastName, Phone, Email, Address FROM Customers"; 
    
    try (Connection conn = DBConnection.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            // Instantiate the 6-argument Customer object
            Customer customer = new Customer(
                rs.getInt("CustomerID"),
                rs.getString("FirstName"),
                rs.getString("LastName"),
                rs.getString("Phone"),
                rs.getString("Email"),
                rs.getString("Address") // <-- Read the new Address field
            );

            // Add the 6 fields to the table model row
            Object[] rowData = {
                customer.getCustomerID(),
                customer.getFirstName(),
                customer.getLastName(),
                customer.getPhone(),
                customer.getEmail(),
                customer.getAddress() // <-- Add to the row
            };
            customerTableModel.addRow(rowData);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Customer DB Read Error: " + e.getMessage(),
            "SQL Error - Customers", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void initSupplierTable() {
    String[] columnHeaders = {"ID", "Company Name", "Contact Person", 
                              "Phone", "Email", "Address"};
                                
    supplierTableModel = new DefaultTableModel(columnHeaders, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };
    supplierTable.setModel(supplierTableModel);
}
    
    public void loadSupplierData() { 
    supplierTableModel.setRowCount(0); 
    
    String sql = "SELECT SupplierID, CompanyName, ContactPerson, Phone, Email, Address FROM Suppliers";
    

    try (Connection conn = DBConnection.getConnection();
         Statement stmt = conn.createStatement();        
         ResultSet rs = stmt.executeQuery(sql)) {       

     
        while (rs.next()) {
           
            Supplier supplier = new Supplier(
                rs.getInt("SupplierID"),
                rs.getString("CompanyName"),
                rs.getString("ContactPerson"),
                rs.getString("Phone"),
                rs.getString("Email"),
                rs.getString("Address")
            );

            Object[] rowData = {
                supplier.getSupplierID(),
                supplier.getCompanyName(),
                supplier.getContactPerson(),
                supplier.getPhone(),
                supplier.getEmail(),
                supplier.getAddress()
            };
            supplierTableModel.addRow(rowData);
        }
        
    } catch (SQLException e) {
        
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Database Connection/Query Failed: " + e.getMessage() + 
            "\nCheck DBConnection.java credentials and MySQL server status.", 
            "SQL Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void initStockTable() {
        String[] cols = {"ID","SupplierID","ProductID","Quantity","Type","Date"};
        stockTableModel = new DefaultTableModel(cols,0) { @Override public boolean isCellEditable(int r,int c){return false;} };
        stockTable.setModel(stockTableModel);
    }
    
     public void loadStockData() {
        stockTableModel.setRowCount(0);
        String sql = "SELECT StockLogID, SupplierID, ProductID, Quantity, TransactionType, TransactionDate FROM StockLogs";
        try (Connection conn = DBConnection.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                Object[] row = { rs.getInt("StockLogID"), rs.getInt("SupplierID"), rs.getInt("ProductID"), rs.getInt("Quantity"), rs.getString("TransactionType"), rs.getString("TransactionDate") };
                stockTableModel.addRow(row);
            }
         } catch (SQLException e) {
              JOptionPane.showMessageDialog(this, "Stock Log DB Read Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
         }
     }
    private void initTransportTable() {
    
    String[] columnHeaders = {"ID", "Contact Person", "Phone", "Courier Company"};
    
    transportTableModel = new DefaultTableModel(columnHeaders, 0) {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };
    transportTable.setModel(transportTableModel);
}
    
    public void loadTransportData() {
    transportTableModel.setRowCount(0);
    
    String sql = "SELECT TransportID, ContactPerson, Phone, CourierCompany FROM Transports";
    
    try (Connection conn = DBConnection.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            
            Transport transport = new Transport(
                rs.getInt("TransportID"),
                rs.getString("ContactPerson"),
                rs.getString("Phone"),
                rs.getString("CourierCompany")
            );

           
            Object[] rowData = {
                transport.getTransportID(),
                transport.getContactPerson(),
                transport.getPhone(),
                transport.getCourierCompany()
            };
            transportTableModel.addRow(rowData);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Transport DB Read Error: " + e.getMessage() + 
            "\nCheck your DBConnection and MySQL server status.",
            "SQL Error - Transport", JOptionPane.ERROR_MESSAGE);
    }
}
    
     private void initTransportLogTable() {
        String[] cols = {"LogID","TransportID","RequestID","Delivery","Arrival","Status"};
        transportLogTableModel = new DefaultTableModel(cols,0) { @Override public boolean isCellEditable(int r,int c){return false;} };
        transportLogTable.setModel(transportLogTableModel);
    }
     
     // ----- Transport Log UI/DB -----
    private void setupTransportLogPanel() {
        transportLogTable = new javax.swing.JTable();
        searchTransLog = new javax.swing.JTextField(15);
        addTransportLogBtn = new javax.swing.JButton("Add");
        transLogPanel.setLayout(new BorderLayout());
        javax.swing.JPanel top = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        top.add(new javax.swing.JLabel("Transport Logs"));
        top.add(searchTransLog);
        top.add(addTransportLogBtn);
        transLogPanel.add(top, BorderLayout.NORTH);
        transLogPanel.add(new javax.swing.JScrollPane(transportLogTable), BorderLayout.CENTER);

        addTransportLogBtn.addActionListener(evt -> {
            addTransportLog frm = new addTransportLog(this);
            frm.setVisible(true);
        });
        
        searchTransLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    DefaultTableModel ob = (DefaultTableModel) transportLogTable.getModel();
                    TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
                    transportLogTable.setRowSorter(obj);
                    obj.setRowFilter(RowFilter.regexFilter(searchTransLog.getText()));
                } catch (Exception ex) { }
            }
        });
    }
    
    public void loadTransportLogData() {
        transportLogTableModel.setRowCount(0);
        String sql = "SELECT LogID, TransportID, RequestID, DeliveryDate, ArrivalDate, Status FROM TransportLogs";
        try (Connection conn = DBConnection.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                Object[] row = { rs.getInt("LogID"), rs.getInt("TransportID"), rs.getInt("RequestID"), rs.getString("DeliveryDate"), rs.getString("ArrivalDate"), rs.getString("Status") };
                transportLogTableModel.addRow(row);
            }
          } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Transport Log DB Read Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
          }
    }
     // ----- Return Request UI/DB -----
    private void setupReturnRequestPanel() {
        returnRequestTable = new javax.swing.JTable();
        searchReturn = new javax.swing.JTextField(15);
        addReturnRequestBtn = new javax.swing.JButton("Add");

        returnRequestPanel.setLayout(new BorderLayout());
        javax.swing.JPanel top = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        top.add(new javax.swing.JLabel("Return Requests"));
        top.add(searchReturn);
        top.add(addReturnRequestBtn);
        returnRequestPanel.add(top, BorderLayout.NORTH);

        javax.swing.JScrollPane sp = new javax.swing.JScrollPane(returnRequestTable);
        returnRequestPanel.add(sp, BorderLayout.CENTER);

        addReturnRequestBtn.addActionListener(evt -> {
            addReturnRequest frm = new addReturnRequest(this);
            frm.setVisible(true);
        });

        searchReturn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    DefaultTableModel ob = (DefaultTableModel) returnRequestTable.getModel();
                    TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
                    returnRequestTable.setRowSorter(obj);
                    obj.setRowFilter(RowFilter.regexFilter(searchReturn.getText()));
                } catch (Exception ex) { }
            }
        });
    }

    private void initReturnRequestTable() {
        String[] cols = {"ID", "OrderID", "CustomerID", "ProductID", "Reason", "Date", "Status"};
        returnRequestTableModel = new DefaultTableModel(cols, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        returnRequestTable.setModel(returnRequestTableModel);
    }
    
    /**
     * @param args the command line arguments
     */
   public void loadReturnRequestData() throws SQLException {
        returnRequestTableModel.setRowCount(0);
        String sql = "SELECT RequestID, OrderID, CustomerID, ProductID, ReturnReason, RequestDate, Status FROM ReturnRequests";
        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("RequestID"),
                    rs.getInt("OrderID"),
                    rs.getInt("CustomerID"),
                    rs.getInt("ProductID"),
                    rs.getString("ReturnReason"),
                    rs.getString("RequestDate"),
                    rs.getString("Status")
                };
                returnRequestTableModel.addRow(row);
            }
           } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Return Request DB Read Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
           }
          }

        
     // ----- Stock Log UI/DB -----     // ----- Stock Log UI/DB -----
    private void setupStockPanel() {
        stockTable = new javax.swing.JTable();
        searchStock = new javax.swing.JTextField(15);
        addStockBtn = new javax.swing.JButton("Add");
        stockPanel.setLayout(new BorderLayout());
        javax.swing.JPanel top = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        top.add(new javax.swing.JLabel("Stock Log"));
        top.add(searchStock);
        top.add(addStockBtn);
        stockPanel.add(top, BorderLayout.NORTH);
        stockPanel.add(new javax.swing.JScrollPane(stockTable), BorderLayout.CENTER);

        addStockBtn.addActionListener(evt -> {
            addStockLog frm = new addStockLog(this);
            frm.setVisible(true);
        }); 
        
        searchStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    DefaultTableModel ob = (DefaultTableModel) stockTable.getModel();
                    TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
                    stockTable.setRowSorter(obj);
                    obj.setRowFilter(RowFilter.regexFilter(searchStock.getText()));
                } catch (Exception ex) { }
            }
        });
    
    }
    private void generateReturnsAnalysisReport() {
        checkReportDirectory();
        String sql = "SELECT "
               + "    c.FirstName, c.LastName, "
               + "    p.ProductName, p.Manufacturer AS ProductType, "
               + "    rr.ReturnReason, "
               + "    COUNT(rr.RequestID) as TotalReturns "
               + "FROM ReturnRequests rr "
               + "JOIN Products p ON rr.ProductID = p.ProductID "
               + "JOIN Orders o ON rr.OrderID = o.OrderID "
               + "JOIN Customers c ON o.CustomerID = c.CustomerID "
               + "GROUP BY c.CustomerID, p.ProductID, rr.ReturnReason "
               + "ORDER BY TotalReturns DESC";
    
        String filePath = REPORTS_DIR + "ReturnsAnalysis.pdf"; // PDF extension
        String title = "Returns Analysis Report";
        int columnCount = 6; // FirstName, LastName, ProductName, ProductType, ReturnReason, TotalReturns

        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            // pdf export
            PdfExporter.exportReportToPdf(this, title, rs, filePath, columnCount);

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error generating Returns Analysis Report", e);
            JOptionPane.showMessageDialog(this, "Database Error:\n" + e.getMessage(), "Report Error", JOptionPane.ERROR_MESSAGE);

        }
        
    }
    
     // ----- Orders UI/DB -----
    private void setupOrderPanel() {
        orderTable = new javax.swing.JTable();
        searchOrder = new javax.swing.JTextField(15);
        addOrderBtn = new javax.swing.JButton("Add");
        salesPanel.setLayout(new BorderLayout());
        javax.swing.JPanel top = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        top.add(new javax.swing.JLabel("Orders"));
        top.add(searchOrder);
        top.add(addOrderBtn);
        salesPanel.add(top, BorderLayout.NORTH);
        salesPanel.add(new javax.swing.JScrollPane(orderTable), BorderLayout.CENTER);

        addOrderBtn.addActionListener(evt -> {
            addOrder frm = new addOrder(this);
            frm.setVisible(true);
        });

        searchOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    DefaultTableModel ob = (DefaultTableModel) orderTable.getModel();
                    TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
                    orderTable.setRowSorter(obj);
                    obj.setRowFilter(RowFilter.regexFilter(searchOrder.getText()));
                } catch (Exception ex) { }
            }
        });
    }
    
    private void initOrderTable() {
        String[] cols = {"OrderID", "CustomerID", "OrderDate", "Status"};
        orderTableModel = new DefaultTableModel(cols, 0) { @Override public boolean isCellEditable(int r, int c){return false;} };
        orderTable.setModel(orderTableModel);
    }
    
    public void loadOrderData() {
        orderTableModel.setRowCount(0);
        String sql = "SELECT OrderID, CustomerID, OrderDate, OrderStatus FROM Orders";
        try (Connection conn = DBConnection.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                Object[] row = { rs.getInt("OrderID"), rs.getInt("CustomerID"), rs.getString("OrderDate"), rs.getString("OrderStatus") };
                orderTableModel.addRow(row);
            }
           } catch (SQLException e) {
               JOptionPane.showMessageDialog(this, "Order DB Read Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
           }
    }
    
    
    
    private void generateCustomerEngagementReport(int year, int month) {
        checkReportDirectory();

        String sql = "SELECT c.FirstName, c.LastName, p.ProductName, SUM(oi.Quantity) as TotalBought " +
                     "FROM Customers c " +
                     "JOIN Orders o ON c.CustomerID = o.CustomerID " +
                     "JOIN OrderItems oi ON o.OrderID = oi.OrderID " +
                     "JOIN Products p ON oi.ProductID = p.ProductID " +
                     "WHERE YEAR(o.OrderDate) = ? AND MONTH(o.OrderDate) = ? " +
                     "GROUP BY c.CustomerID, p.ProductID " +
                     "ORDER BY c.CustomerID, TotalBought DESC";

        String filePath = REPORTS_DIR + String.format("CustomerEngagement_%d_%02d.pdf", year, month);
        String title = String.format("Customer Engagement Report (%d-%02d)", year, month);
        int columnCount = 4; // FirstName, LastName, ProductName, TotalBought

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, year);
            pstmt.setInt(2, month);

            try (ResultSet rs = pstmt.executeQuery()) {
                PdfExporter.exportReportToPdf(this, title, rs, filePath, columnCount);
            }

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error generating Customer Engagement Report", e);
            JOptionPane.showMessageDialog(this, "Database Error:\n" + e.getMessage(), "Report Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void promptCustomerEngagementReport() {
        String yearStr = JOptionPane.showInputDialog(this, "Enter Year (e.g., 2025):", "Customer Engagement Report", JOptionPane.QUESTION_MESSAGE);
        if (yearStr == null || yearStr.trim().isEmpty()) return;

        String monthStr = JOptionPane.showInputDialog(this, "Enter Month (1-12):", "Customer Engagement Report", JOptionPane.QUESTION_MESSAGE);
        if (monthStr == null || monthStr.trim().isEmpty()) return;

        try {
            int year = Integer.parseInt(yearStr.trim());
            int month = Integer.parseInt(monthStr.trim());
            generateCustomerEngagementReport(year, month);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Year or Month entered. Please use numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void generateSupplierOrderReport(int year, int month) {
        checkReportDirectory();

        String sql = "SELECT s.CompanyName, SUM(sl.Quantity) as TotalOrdered " +
                     "FROM Suppliers s " +
                     "JOIN StockLogs sl ON s.SupplierID = sl.SupplierID " +
                     "WHERE YEAR(sl.TransactionDate) = ? AND MONTH(sl.TransactionDate) = ? " +
                     "GROUP BY s.SupplierID " +
                     "ORDER BY TotalOrdered DESC";

        String filePath = REPORTS_DIR + String.format("SupplierOrders_%d_%02d.pdf", year, month);
        String title = String.format("Supplier Order Report (%d-%02d)", year, month);
        int columnCount = 2; // CompanyName, TotalOrdered

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, year);
            pstmt.setInt(2, month);

            try (ResultSet rs = pstmt.executeQuery()) {
                PdfExporter.exportReportToPdf(this, title, rs, filePath, columnCount);
            }

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error generating Supplier Order Report", e);
            JOptionPane.showMessageDialog(this, "Database Error:\n" + e.getMessage(), "Report Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void promptSupplierOrderReport() {
        String yearStr = JOptionPane.showInputDialog(this, "Enter Year (e.g., 2025):", "Supplier Order Report", JOptionPane.QUESTION_MESSAGE);
        if (yearStr == null || yearStr.trim().isEmpty()) return;

        String monthStr = JOptionPane.showInputDialog(this, "Enter Month (1-12):", "Supplier Order Report", JOptionPane.QUESTION_MESSAGE);
        if (monthStr == null || monthStr.trim().isEmpty()) return;

        try {
            int year = Integer.parseInt(yearStr.trim());
            int month = Integer.parseInt(monthStr.trim());
            generateSupplierOrderReport(year, month);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Year or Month entered. Please use numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void generateTransportEfficiencyReport(int year, int month) {
        checkReportDirectory();

        // SQL filters by ArrivalDate (for the month/year) and a completion status (e.g., 'Delivered')
        String sql = "SELECT t.CourierCompany, COUNT(tl.LogID) as CompletedReturns " +
                     "FROM Transports t " +
                     "JOIN TransportLogs tl ON t.TransportID = tl.TransportID " +
                     "WHERE tl.Status = 'Delivered' " + // Assuming 'Delivered' means completed return transport
                     "AND YEAR(tl.ArrivalDate) = ? AND MONTH(tl.ArrivalDate) = ? " + 
                     "GROUP BY t.TransportID " +
                     "ORDER BY CompletedReturns DESC";

        String filePath = REPORTS_DIR + String.format("TransportEfficiency_%d_%02d.pdf", year, month);
        String title = String.format("Transport Efficiency Report (%d-%02d)", year, month);
        int columnCount = 2; // CourierCompany, CompletedReturns

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, year);
            pstmt.setInt(2, month);

            try (ResultSet rs = pstmt.executeQuery()) {
                PdfExporter.exportReportToPdf(this, title, rs, filePath, columnCount);
            }

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error generating Transport Efficiency Report", e);
            JOptionPane.showMessageDialog(this, "Database Error:\n" + e.getMessage(), "Report Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void promptTransportEfficiencyReport() {
    String yearStr = JOptionPane.showInputDialog(this, "Enter Year (e.g., 2025):", "Transport Efficiency Report", JOptionPane.QUESTION_MESSAGE);
    if (yearStr == null || yearStr.trim().isEmpty()) return;

    String monthStr = JOptionPane.showInputDialog(this, "Enter Month (1-12):", "Transport Efficiency Report", JOptionPane.QUESTION_MESSAGE);
    if (monthStr == null || monthStr.trim().isEmpty()) return;

    try {
        int year = Integer.parseInt(yearStr.trim());
        int month = Integer.parseInt(monthStr.trim());
        generateTransportEfficiencyReport(year, month);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Year or Month entered. Please use numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomer;
    private javax.swing.JButton addProduct;
    private javax.swing.JButton addSupplier;
    private javax.swing.JButton addTransport;
    private javax.swing.JMenuItem customerEngagementMenu;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable prodTable;
    private javax.swing.JPanel productPanel;
    private javax.swing.JPanel returnRequestPanel;
    private javax.swing.JMenuItem returnsAnalysisMenu;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JTextField searchCust;
    private javax.swing.JTextField searchProd;
    private javax.swing.JTextField searchSupp;
    private javax.swing.JTextField searchTranspo;
    private javax.swing.JPanel stockPanel;
    private javax.swing.JLabel suppLabel;
    private javax.swing.JMenuItem suppOrderMenu;
    private javax.swing.JPanel supplierPanel;
    private javax.swing.JTable supplierTable;
    private javax.swing.JMenuItem transEfficiencyMenu;
    private javax.swing.JPanel transLogPanel;
    private javax.swing.JPanel transportPanel;
    private javax.swing.JTable transportTable;
    private javax.swing.JButton updateCustomer;
    private javax.swing.JButton updateProduct;
    private javax.swing.JButton updateSupplier;
    private javax.swing.JButton updateTransport;
    // End of variables declaration//GEN-END:variables
}
